Q.push(
{id:13,s:"mat",d:"fácil",q:"Quanto é 20% de 350?",o:["60","70","80","90"],a:1,e:"10% de 350 é 35; portanto, 20% é 70."},
{id:14,s:"mat",d:"médio",q:"Uma produção aumentou de 400 para 460 unidades. Qual foi o aumento percentual?",o:["10%","12%","15%","20%"],a:2,e:"O aumento foi 60. Fazendo 60 ÷ 400 × 100, obtemos 15%."},
{id:15,s:"mat",d:"médio",q:"Três máquinas fazem 900 peças em 5 horas. No mesmo ritmo, uma máquina faz quantas peças em 5 horas?",o:["200","250","300","450"],a:2,e:"900 peças divididas igualmente por 3 máquinas resultam em 300."},
{id:16,s:"mat",d:"difícil",q:"Um salário de R$ 1.500 recebeu aumento de 8% e depois desconto de 5%. Qual o valor final?",o:["R$ 1.530","R$ 1.539","R$ 1.540","R$ 1.620"],a:1,e:"1.500 × 1,08 = 1.620; depois 1.620 × 0,95 = R$ 1.539."},
{id:17,s:"mat",d:"fácil",q:"Qual é o resultado de 48 ÷ 6 + 3 × 4?",o:["20","32","44","68"],a:0,e:"Primeiro divisão e multiplicação: 8 + 12 = 20."},
{id:18,s:"mat",d:"difícil",q:"Se 5/8 de 240 funcionários participaram de um treinamento, quantos participaram?",o:["120","140","150","160"],a:2,e:"240 ÷ 8 = 30; 30 × 5 = 150."},
{id:19,s:"por",d:"fácil",q:"Qual alternativa apresenta sinônimo de “eficiente”?",o:["Lento","Produtivo","Impreciso","Distraído"],a:1,e:"Produtivo é a opção de sentido mais próximo de eficiente."},
{id:20,s:"por",d:"médio",q:"Em “Embora estivesse cansado, terminou a tarefa”, a palavra “embora” expressa:",o:["Causa","Condição","Concessão","Finalidade"],a:2,e:"Embora introduz uma ideia de concessão, ou seja, um contraste que não impede a ação."},
{id:21,s:"por",d:"médio",q:"Assinale a opção com pontuação adequada:",o:["Gustavo revise os cálculos.","Gustavo, revise os cálculos.","Gustavo revise, os cálculos.","Gustavo, revise, os cálculos."],a:1,e:"O vocativo “Gustavo” deve ser separado por vírgula."},
{id:22,s:"por",d:"difícil",q:"Em “Os relatórios foram entregues pela equipe”, a oração está na voz:",o:["Ativa","Passiva","Reflexiva","Imperativa"],a:1,e:"O sujeito recebe a ação, caracterizando voz passiva."},
{id:23,s:"por",d:"fácil",q:"Qual palavra completa corretamente: “Não sei ___ ele faltou”?",o:["porque","por que","porquê","por quê"],a:1,e:"Em pergunta indireta, usa-se “por que” separado."},
{id:24,s:"por",d:"difícil",q:"A frase “Fazem dois anos que trabalho aqui” deve ser corrigida para:",o:["Faz dois anos que trabalho aqui","Fazem dois ano que trabalho aqui","Faziam dois anos que trabalho aqui","Há fazem dois anos que trabalho aqui"],a:0,e:"O verbo fazer indicando tempo decorrido é impessoal e fica no singular."},
{id:25,s:"log",d:"fácil",q:"Complete: 5, 10, 15, 20, ___",o:["22","24","25","30"],a:2,e:"A sequência aumenta de 5 em 5; o próximo termo é 25."},
{id:26,s:"log",d:"médio",q:"Complete: 1, 4, 9, 16, ___",o:["20","24","25","32"],a:2,e:"São quadrados perfeitos: 1², 2², 3², 4² e 5² = 25."},
{id:27,s:"log",d:"médio",q:"Se nenhum gerente é estagiário e Paula é gerente, então:",o:["Paula é estagiária","Paula não é estagiária","Paula pode ser estagiária","Nada pode ser concluído"],a:1,e:"A regra exclui qualquer gerente do grupo dos estagiários."},
{id:28,s:"log",d:"difícil",q:"A é mais alto que B. C é mais baixo que B. Quem é o mais alto?",o:["A","B","C","Não é possível saber"],a:0,e:"Se A > B e B > C, então A é o mais alto."},
{id:29,s:"log",d:"fácil",q:"Livro está para leitura assim como garfo está para:",o:["Cozinha","Comida","Mesa","Alimentação"],a:3,e:"O livro é instrumento de leitura; o garfo é instrumento de alimentação."},
{id:30,s:"log",d:"difícil",q:"Três caixas são identificadas por A, B e C. A não está ao lado de C. Se estão em fila, qual caixa deve ficar no meio?",o:["A","B","C","Qualquer uma"],a:1,e:"Para A e C não ficarem lado a lado, B precisa separá-las no meio."}
);
Q.forEach((q,i)=>{if(!q.d)q.d=i%3===0?"fácil":i%3===1?"médio":"difícil"});
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const shuffledQ=q=>{const tagged=q.o.map((text,i)=>({text,ok:i===q.a})),mix=shuffle(tagged);return{...q,o:mix.map(x=>x.text),a:mix.findIndex(x=>x.ok)}};
const oldStartPractice=startPractice;
startPractice=function(f="all"){let s=f;if(f==="weak"){let sc=scores();s=Object.keys(sc).sort((a,b)=>(sc[a][1]?sc[a][0]/sc[a][1]:0)-(sc[b][1]?sc[b][0]/sc[b][1]:0))[0]}const level=document.querySelector("#levelFilter")?.value||"all";pool=shuffle((s==="all"?Q:Q.filter(q=>q.s===s)).filter(q=>level==="all"||q.d===level)).map(shuffledQ);qi=0;sessionRight=0;sessionDone=0;locked=false;view("practice");renderQuestion()};
const practiceFilters=document.querySelector("#practice .filterrow");practiceFilters.insertAdjacentHTML("beforeend",'<select id="levelFilter" class="chip" aria-label="Nível de dificuldade"><option value="all">Todos os níveis</option><option value="fácil">Fácil</option><option value="médio">Médio</option><option value="difícil">Difícil</option></select>');document.querySelector("#levelFilter").onchange=()=>startPractice(document.querySelector(".chip.active")?.dataset.filter||"all");
document.querySelector(".navbox .navbtn[data-view='exam']").insertAdjacentHTML("beforebegin",'<button class="navbtn" data-view="theory">Resumos</button>');
document.querySelector(".bottomnav button[data-view='exam']").insertAdjacentHTML("beforebegin",'<button data-view="theory"><b>≡</b>Resumo</button>');
document.querySelector("#plan").insertAdjacentHTML("beforebegin",'<section class="section" id="theory"><div class="section-title"><h2>Resumo rápido</h2><p>O essencial para revisar antes da prova</p></div><div class="theory-grid"><article class="card theory-card"><span class="level">MATEMÁTICA</span><h3>Fórmulas essenciais</h3><div class="formula">Porcentagem = valor × taxa ÷ 100</div><div class="formula">Média = soma dos valores ÷ quantidade</div><div class="formula">Regra de três: multiplique em cruz</div><p class="sub">Respeite a ordem: parênteses, multiplicação/divisão e soma/subtração.</p></article><article class="card theory-card"><span class="level">PORTUGUÊS</span><h3>Leitura e gramática</h3><div class="formula">Leia primeiro o comando da questão.</div><div class="formula">Procure a resposta no contexto, não na memória.</div><div class="formula">Sujeito plural pede verbo no plural.</div><p class="sub">Vocativo usa vírgula. “Fazer” indicando tempo fica no singular.</p></article><article class="card theory-card"><span class="level">LÓGICA</span><h3>Padrões e dedução</h3><div class="formula">Teste diferença, multiplicação e alternância.</div><div class="formula">Transforme frases em regras curtas.</div><div class="formula">Elimine opções impossíveis primeiro.</div><p class="sub">Não acrescente informações que o enunciado não forneceu.</p></article></div><div class="section-title"><h2>Histórico de simulados</h2><p>Sua evolução fica salva neste aparelho</p></div><article class="card" id="historyBox"></article></section>');
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));
function renderHistory(){const h=[...(state.examHistory||[])].reverse();document.querySelector("#historyBox").innerHTML=h.length?'<table class="history-table"><thead><tr><th>Data</th><th>Nota</th><th>Tempo</th></tr></thead><tbody>'+h.map(x=>'<tr><td>'+new Date(x.date).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})+'</td><td><b>'+x.right+'/'+Q.length+'</b></td><td>'+Math.floor(x.used/60)+'min '+x.used%60+'s</td></tr>').join("")+'</tbody></table>':'<div class="empty">Faça o primeiro simulado completo para iniciar seu histórico.</div>'}
const oldView=view;view=function(id){oldView(id);if(id==="theory")renderHistory()};
document.querySelector(".info").parentElement.querySelector(".actions")?.insertAdjacentHTML("beforeend",'<a class="btn light" href="https://waze.com/ul?q=Schaeffler%20Brasil%20Av.%20Independencia%203500-A%20Sorocaba%20SP&navigate=yes" target="_blank" rel="noopener">Abrir no Waze ↗</a>');
document.body.insertAdjacentHTML("beforeend",'<div class="settings" aria-label="Acessibilidade"><button id="themeToggle" title="Alternar tema">◐</button><button id="fontDown" title="Diminuir texto">A−</button><button id="fontUp" title="Aumentar texto">A+</button></div>');
let scale=+(localStorage.studyFont||1);document.documentElement.style.setProperty("--font-scale",scale);if(localStorage.studyDark==="1")document.body.classList.add("dark");document.querySelector("#themeToggle").onclick=()=>{document.body.classList.toggle("dark");localStorage.studyDark=document.body.classList.contains("dark")?"1":"0"};document.querySelector("#fontDown").onclick=()=>{scale=Math.max(.9,scale-.1);document.documentElement.style.setProperty("--font-scale",scale);localStorage.studyFont=scale};document.querySelector("#fontUp").onclick=()=>{scale=Math.min(1.25,scale+.1);document.documentElement.style.setProperty("--font-scale",scale);localStorage.studyFont=scale};
function confetti(){for(let i=0;i<70;i++){const c=document.createElement("i");c.className="confetti";c.style.left=Math.random()*100+"vw";c.style.background=["#00a651","#65cf8f","#fff","#111"][i%4];c.style.setProperty("--drift",(Math.random()*240-120)+"px");c.style.animationDelay=Math.random()*.7+"s";document.body.appendChild(c);setTimeout(()=>c.remove(),3600)}}
const baseFinish=finishExam;finishExam=function(){const unanswered=Q.filter(q=>examAnswers[q.id]===undefined).length;if(examSecs>0&&unanswered&&!confirm("Ainda há "+unanswered+" questão(ões) sem resposta. Deseja finalizar mesmo assim?"))return;baseFinish();const last=state.examHistory[state.examHistory.length-1];if(last&&last.right/Q.length>=.7){confetti();toast("Parabéns! Excelente resultado.")}renderHistory()};
let warned={};setInterval(()=>{if(examRun){[[1800,"Faltam 30 minutos."],[600,"Faltam 10 minutos."],[300,"Faltam 5 minutos."]].forEach(([t,m])=>{if(examSecs===t&&!warned[t]){warned[t]=1;toast(m)}})}},1000);
document.querySelector("#examRunning .exam-top").insertAdjacentHTML("afterend",'<div class="exam-warning">Responda todas as questões. Você pode voltar antes de finalizar.</div>');
document.querySelector(".hero p").insertAdjacentHTML("afterend",'<div class="offline-badge">Disponível offline após a primeira abertura</div>');
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
updateAll();renderHistory();
